# Site settings
title: The Time Warp
email: contact@cityzendata.com
description: The Time Warp
filename: the-time-warp
baseurl: ""
url: "http://cityzendata.com"
twitter_username: CityzenData

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
