# Site settings
title: Cityzen Data
email: contact@cityzendata.com
description: "Cityzen Data's blog"
baseurl: "/"
url: "http://cityzendata.com"
twitter_username: CityzenData

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
